### ISSUE TITLE
let `= ` resolve to ` = `

### ISSUE THREAD

**Issue by sooheon** [genovese/ess-smart-equals#1]
This package comes very close to my desired behaviour with the caveat that I now cannot keep spaces around the `=` operator as recommended by most style guides. I think short of a way to interactively be aware of whether the point is inside a function call or not, the second best way would be to let a 'unspaced' `=` followed by a space expand to `=`.

edit because the markdown is unclear. I want it to expand to `space=space`.

**Comment by genovese** [comment]
Interesting, thanks.  I think that should be doable pretty easily, and I'll
put that on my list.

Personally, I don't agree with the style guides that suggest putting spaces
around = for
default arguments. Because = can be used as assignment (and you see it used
as such
in a lot of code), the spaced equals always makes me pause as to the
intention.
Because I always put spaces around my binary operators, an unspaced = for
default args distinguishes them syntactically. For my style, I am
consistent in
using an unspaced = for default arguments to make that distinction visually
clearer.
This is what motivated the usage in the package.

But that said, I'm happy to support the usage you suggest and will try to
add that
functionality as soon as I can.

Best, Chris

**Comment by jabranham** [comment]
Hi - 

I was wondering if any progress has been made on this front? This package seems like a great idea, but I do like spaces around the equals sign in function calls.

If there's something I can do to help, definitely let me know.

**Comment by genovese** [comment]
Thanks, Alex.  Sorry for the slow response; I've been a bit crushed
at work but hope to get to this really soon.

**Comment by jmburgos** [comment]
No progress in this issue?  I would also like to have an "=" become an " = ". Thanks!

**Comment by genovese** [comment]
I'm nearly ready to push a major update that allows this behavior to be controlled while adding a lot of improved functionality. Sorry for the delay on this.

**Comment by genovese** [comment]
As of version 0.3.0, a complete and fully-featured rewrite, this (single spaces around '=') is now the default behavior, and the padding is fully configurable. Thanks for your feedback, and I'm sorry this took so long to resolve.
