### ISSUE TITLE
Error since ESS update

### ISSUE THREAD

**Issue by hummuscience** [genovese/ess-smart-equals#2]
(use-package ess-smart-equals)
 leads now to the following error when running emacs:

`Error (use-package): ess-smart-equals/:catch: Symbol’s value as variable is void: ess-S-assign
`

**Comment by dangom** [comment]
For those who land on this issue.
I've partially fixed the mode so that it works with the latest ESS releases.
I say partially because the fix has only been tested with R ( I don't know anything about other S languages). I also don't know what the previous behaviour of this mode looked like, since I just started coding in R, so I can't compare, but things work OK for me.

Code in my branch [here](https://github.com/dangom/ess-smart-equals/commit/8a4aa9e4752cc18a914369a6665488a6c380bfee).

**Comment by genovese** [comment]
I'm very nearly ready to push a major update that fixes this issue and more, adding a lot of improved functionality. Sorry to have taken so long getting to this; time got away from me.  I'm testing the update, and it should be up ready in a couple days at most.

Thanks @dangom; feel free to submit a PR. Since the new version is a complete rewrite, it could be useful to integrate your fix into the old (i.e., current) version.
